"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PermissionNodes = exports.Perms = exports.Permissions = void 0;
// @deprecated Use PermissionNodes
var Permissions;
(function (Permissions) {
    Permissions[Permissions["VIEW_STAFF_DASHBOARD"] = 1] = "VIEW_STAFF_DASHBOARD";
    Permissions[Permissions["MANAGE_ORDERS"] = 2] = "MANAGE_ORDERS";
    Permissions[Permissions["VIEW_FOOD_LOOKUP"] = 4] = "VIEW_FOOD_LOOKUP";
    Permissions[Permissions["MANAGE_APPEALS"] = 8] = "MANAGE_APPEALS";
    Permissions[Permissions["MANAGE_APPEALS_ADMIN"] = 16] = "MANAGE_APPEALS_ADMIN";
    Permissions[Permissions["VIEW_BACKLOG"] = 32] = "VIEW_BACKLOG";
    Permissions[Permissions["MANAGE_FOOD_LOOKUP"] = 64] = "MANAGE_FOOD_LOOKUP";
    Permissions[Permissions["SUBMIT_ON_LEAVE_REQUEST"] = 128] = "SUBMIT_ON_LEAVE_REQUEST";
    Permissions[Permissions["MANAGE_ON_LEAVE_REQUESTS"] = 256] = "MANAGE_ON_LEAVE_REQUESTS";
    Permissions[Permissions["MANAGE_USERS"] = 512] = "MANAGE_USERS";
    Permissions[Permissions["UPDATE_USER_RANK"] = 1024] = "UPDATE_USER_RANK";
    Permissions[Permissions["BAN_USERS"] = 2048] = "BAN_USERS";
    Permissions[Permissions["MANAGE_STAFF_REMOVALS"] = 4096] = "MANAGE_STAFF_REMOVALS";
    Permissions[Permissions["MANAGE_BLACKLISTS"] = 8192] = "MANAGE_BLACKLISTS";
    Permissions[Permissions["MANAGE_RANKS"] = 16384] = "MANAGE_RANKS";
    Permissions[Permissions["BYPASS_PURGE"] = 32768] = "BYPASS_PURGE";
    Permissions[Permissions["MANAGE_DELIVERY_MESSAGES"] = 65536] = "MANAGE_DELIVERY_MESSAGES";
    Permissions[Permissions["VIEW_RECRUITMENT_RESPONSE"] = 131072] = "VIEW_RECRUITMENT_RESPONSE";
    Permissions[Permissions["RECRUITMENT_MANAGER"] = 262144] = "RECRUITMENT_MANAGER";
    Permissions[Permissions["MANAGE_WARNINGS"] = 524288] = "MANAGE_WARNINGS";
    Permissions[Permissions["MANAGE_KNOWLEDGE_BASE"] = 1048576] = "MANAGE_KNOWLEDGE_BASE";
    Permissions[Permissions["VIEW_MANAGEMENT_STATISTICS"] = 2097152] = "VIEW_MANAGEMENT_STATISTICS";
    Permissions[Permissions["MANAGE_MANAGEMENT_STATISTICS"] = 4194304] = "MANAGE_MANAGEMENT_STATISTICS";
    Permissions[Permissions["SUPER_ADMIN"] = 8388608] = "SUPER_ADMIN";
    Permissions[Permissions["VIEW_OWN_ACHIEVEMENTS"] = 16777216] = "VIEW_OWN_ACHIEVEMENTS";
    Permissions[Permissions["MANAGE_ACHIEVEMENTS"] = 33554432] = "MANAGE_ACHIEVEMENTS";
    Permissions[Permissions["MANAGE_TEAMS"] = 67108864] = "MANAGE_TEAMS";
    Permissions[Permissions["MANAGE_SETTINGS"] = 134217728] = "MANAGE_SETTINGS";
    Permissions[Permissions["MANAGE_ANNOUNCEMENT"] = 268435456] = "MANAGE_ANNOUNCEMENT";
})(Permissions = exports.Permissions || (exports.Permissions = {}));
// @deprecated Use PermissionNodes
var Perms;
(function (Perms) {
    Perms[Perms["ViewStaffDashboard"] = 1] = "ViewStaffDashboard";
    Perms[Perms["ManageOrders"] = 2] = "ManageOrders";
    Perms[Perms["ViewFoodLookup"] = 4] = "ViewFoodLookup";
    Perms[Perms["ManageAppeals"] = 8] = "ManageAppeals";
    Perms[Perms["ManageAppealsAdmin"] = 16] = "ManageAppealsAdmin";
    Perms[Perms["ViewBacklog"] = 32] = "ViewBacklog";
    Perms[Perms["ManageFoodLookup"] = 64] = "ManageFoodLookup";
    Perms[Perms["SubmitOnLeaveRequest"] = 128] = "SubmitOnLeaveRequest";
    Perms[Perms["ManageOnLeaveRequests"] = 256] = "ManageOnLeaveRequests";
    Perms[Perms["ManageUsers"] = 512] = "ManageUsers";
    Perms[Perms["UpdateUserRanks"] = 1024] = "UpdateUserRanks";
    Perms[Perms["BanUsers"] = 2048] = "BanUsers";
    Perms[Perms["ManageStaffRemovals"] = 4096] = "ManageStaffRemovals";
    Perms[Perms["ManageBlacklists"] = 8192] = "ManageBlacklists";
    Perms[Perms["ManageRanks"] = 16384] = "ManageRanks";
    Perms[Perms["BypassPurge"] = 32768] = "BypassPurge";
    Perms[Perms["ManageDeliveryMessages"] = 65536] = "ManageDeliveryMessages";
    Perms[Perms["ViewRecruitmentResponse"] = 131072] = "ViewRecruitmentResponse";
    Perms[Perms["RecruitmentManager"] = 262144] = "RecruitmentManager";
    Perms[Perms["ManageWarnings"] = 524288] = "ManageWarnings";
    Perms[Perms["ManageKnowledgeBase"] = 1048576] = "ManageKnowledgeBase";
    Perms[Perms["ViewManagementStatistics"] = 2097152] = "ViewManagementStatistics";
    Perms[Perms["ManageManagementStatistics"] = 4194304] = "ManageManagementStatistics";
    Perms[Perms["SuperAdmin"] = 8388608] = "SuperAdmin";
})(Perms = exports.Perms || (exports.Perms = {}));
var PermissionNodes;
(function (PermissionNodes) {
    PermissionNodes[PermissionNodes["ViewStaffDashboard"] = 1] = "ViewStaffDashboard";
    PermissionNodes[PermissionNodes["ManageOrders"] = 2] = "ManageOrders";
    PermissionNodes[PermissionNodes["ViewFoodLookup"] = 4] = "ViewFoodLookup";
    PermissionNodes[PermissionNodes["ManageAppeals"] = 8] = "ManageAppeals";
    PermissionNodes[PermissionNodes["ManageAppealsAdmin"] = 16] = "ManageAppealsAdmin";
    PermissionNodes[PermissionNodes["ViewBacklog"] = 32] = "ViewBacklog";
    PermissionNodes[PermissionNodes["ManageFoodLookup"] = 64] = "ManageFoodLookup";
    PermissionNodes[PermissionNodes["SubmitOnLeaveRequest"] = 128] = "SubmitOnLeaveRequest";
    PermissionNodes[PermissionNodes["ManageOnLeaveRequests"] = 256] = "ManageOnLeaveRequests";
    PermissionNodes[PermissionNodes["ManageUsers"] = 512] = "ManageUsers";
    PermissionNodes[PermissionNodes["UpdateUserRanks"] = 1024] = "UpdateUserRanks";
    PermissionNodes[PermissionNodes["BanUsers"] = 2048] = "BanUsers";
    PermissionNodes[PermissionNodes["ManageStaffRemovals"] = 4096] = "ManageStaffRemovals";
    PermissionNodes[PermissionNodes["ManageBlacklists"] = 8192] = "ManageBlacklists";
    PermissionNodes[PermissionNodes["ManageRanks"] = 16384] = "ManageRanks";
    PermissionNodes[PermissionNodes["BypassPurge"] = 32768] = "BypassPurge";
    PermissionNodes[PermissionNodes["ManageDeliveryMessages"] = 65536] = "ManageDeliveryMessages";
    PermissionNodes[PermissionNodes["ViewRecruitmentResponse"] = 131072] = "ViewRecruitmentResponse";
    PermissionNodes[PermissionNodes["RecruitmentManager"] = 262144] = "RecruitmentManager";
    PermissionNodes[PermissionNodes["ManageWarnings"] = 524288] = "ManageWarnings";
    PermissionNodes[PermissionNodes["ManageKnowledgeBase"] = 1048576] = "ManageKnowledgeBase";
    PermissionNodes[PermissionNodes["ViewManagementStatistics"] = 2097152] = "ViewManagementStatistics";
    PermissionNodes[PermissionNodes["ManageManagementStatistics"] = 4194304] = "ManageManagementStatistics";
    PermissionNodes[PermissionNodes["SuperAdmin"] = 8388608] = "SuperAdmin";
    PermissionNodes[PermissionNodes["ViewOwnAchievements"] = 16777216] = "ViewOwnAchievements";
    PermissionNodes[PermissionNodes["ManageAchievements"] = 33554432] = "ManageAchievements";
    PermissionNodes[PermissionNodes["ManageTeams"] = 67108864] = "ManageTeams";
    PermissionNodes[PermissionNodes["ManageSettings"] = 134217728] = "ManageSettings";
    PermissionNodes[PermissionNodes["ManageAnnouncement"] = 268435456] = "ManageAnnouncement";
})(PermissionNodes = exports.PermissionNodes || (exports.PermissionNodes = {}));
//# sourceMappingURL=rank.js.map